In [1]:
import numpy as np
print("sss----")
arr = np.array([1,2,3])
print(arr)

sss----
[1 2 3]


In [3]:
arr1 = np.zeros((2,3),dtype=int)
print(arr1)

[[0 0 0]
 [0 0 0]]


In [4]:
arr2 = np.ones((2,3),dtype=int)
print(arr2)

[[1 1 1]
 [1 1 1]]


In [5]:
# 初始化数组,2行3列,值是2025
arr3 = np.full((2,3),2025)
print(arr3)

[[2025 2025 2025]
 [2025 2025 2025]]


### 索引与切片


In [14]:
arr = np.random.randint(1,100,20)
print(arr)
print(arr[2:5])
print(arr[arr > 30])

[22 14 62 24 43 60 66  2 86 83 20 67 45 20 53 48 27 11 36 79]
[62 24 43]
[62 43 60 66 86 83 67 45 53 48 36 79]


In [17]:
name = "ada LOVElace"
print(name.title())

Ada Lovelace
